# Numpy

#### NumPy, which stands for Numerical Python,
#### is a powerful Python library used for numerical computing.
#### It provides a multidimensional array object, various tools for working with arrays, 
#### and a collection of mathematical functions to efficiently operate on these arrays. 
#### NumPy is a fundamental package for scientific computing in Python
#### and is widely used in fields such as data analysis, machine learning, and numerical simulations.

#### The main object in NumPy is the ndarray (N-dimensional array), which is a homogeneous collection of elements of the same data type. These arrays allow efficient storage and manipulation of large sets of numerical data. NumPy also provides functions for creating and manipulating these arrays, as well as performing mathematical operations on them.

#### Here are some of the key features and functions of NumPy:

#### Multidimensional Array: 
    NumPy provides the ndarray object, which allows efficient manipulation of arrays of any dimensionality. 
    This makes it easy to work with matrices, vectors, and higher-dimensional data.

#### Mathematical Functions: 
    NumPy offers a comprehensive set of mathematical functions that operate element-wise on arrays.
    These functions include basic arithmetic operations, trigonometric functions, 
    logarithmic functions, statistical functions, and more.

#### Broadcasting: 
    
    NumPy enables operations between arrays of different shapes and sizes through a mechanism called broadcasting.
    It automatically handles the alignment and computation of arrays with different dimensions,
    making it convenient to perform element-wise operations.

#### Array Manipulation: 
    NumPy provides functions to reshape, concatenate, split, and transpose arrays. 
    These operations are essential for transforming and rearranging data in various ways.

#### Array Operations: 
    NumPy supports various operations on arrays, such as sorting, searching, indexing, slicing, and masking. 
    These capabilities make it easy to extract specific elements or subsets from arrays.

#### Linear Algebra: 
    NumPy includes a comprehensive set of functions for linear algebra operations, 
    such as matrix multiplication, matrix factorization, eigenvalues, and eigenvectors computations. 
    These functions are essential for many scientific and engineering applications.

#### Random Number Generation: 
    NumPy features a random module that provides functions for generating random numbers 
    with different distributions. 
    This is useful for tasks such as simulations, statistical analysis, and generating random data.

#### To use NumPy in your Python code, you need to import it at the beginning of your script 
#### or notebook using the following import statement:




In [1]:
!pip install numpy

In [2]:
import numpy as np

In [8]:
test=np.array([1,3,5,6])
test.max()

6

In [15]:
test=[1,30,2,0,5,"Ali","khan","Moiz"]
num=[]
string=[]
for i in test:
    if isinstance(i, int):
        num.append(i)
        
    else:
        string.append(i)


In [17]:
num.sort()

In [18]:
num

[0, 1, 2, 5, 30]

In [27]:
# Create a 1-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])

In [28]:
arr1

array([1, 2, 3, 4, 5])

In [23]:
# Create a 2-dimensional array
arr2 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [24]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
arr2.ndim

3

In [36]:
result1 = arr1 * 2

In [38]:
result1

array([ 2,  4,  6,  8, 10])

In [41]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [42]:
result2 = np.sin(arr2)


In [43]:
result2

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ],
        [ 0.6569866 ,  0.98935825,  0.41211849]]])

In [20]:
result3 = np.cos(arr2)

In [21]:
result3

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [74]:
result4 = np.tan([[arr2]])

In [75]:
result4

array([[[[[ 1.55740772, -2.18503986, -0.14254654],
          [ 1.15782128, -3.38051501, -0.29100619],
          [ 0.87144798, -6.79971146, -0.45231566]]]]])

In [60]:
trry=[[1,2,3,4,"Nan",5]]


In [71]:
result5 = np.isnan(result4)

In [72]:
result5

array([[[[False, False, False],
         [False, False, False],
         [False, False, False]]]])

In [77]:
result4.shape

(1, 1, 1, 3, 3)

In [85]:
# Reshape the array
reshaped_arr = arr1.reshape(1, 5)
reshaped_arr

array([[1, 2, 3, 4, 5]])

In [79]:
reshaped_arr

array([[1, 2, 3, 4, 5]])

In [80]:
reshaped_arr.ndim

2

In [95]:
quiz=np.array([[20,17,13,5,9,6]])
quiz

array([[20, 17, 13,  5,  9,  6]])

In [98]:
quiz.reshape(-1,2)

array([[20, 17],
       [13,  5],
       [ 9,  6]])

In [102]:
quiz.transpose()

array([[20],
       [17],
       [13],
       [ 5],
       [ 9],
       [ 6]])

In [100]:
quiz.ndim

2

In [56]:
reshaped_arr.dtype

dtype('int64')

In [101]:
result2.transpose()

array([[[ 0.84147098],
        [-0.7568025 ],
        [ 0.6569866 ]],

       [[ 0.90929743],
        [-0.95892427],
        [ 0.98935825]],

       [[ 0.14112001],
        [-0.2794155 ],
        [ 0.41211849]]])

In [60]:
result2

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [62]:
# Compute the mean of the array
mean_value = np.mean(arr2)
mean_value

5.0

In [63]:
# Compute the mean of the array
mean_value = np.mean(result2)
mean_value

0.21724549801193113

In [137]:
# Generate random numbers
random_array = np.random.rand(5,2,2,2,2)
random_array

array([[[[[0.7146573 , 0.26490433],
          [0.15066881, 0.39919882]],

         [[0.10454145, 0.66008216],
          [0.1855954 , 0.7912181 ]]],


        [[[0.39463038, 0.03966952],
          [0.10187056, 0.61124719]],

         [[0.48047063, 0.2048038 ],
          [0.46889679, 0.11965149]]]],



       [[[[0.94859688, 0.48357467],
          [0.24948301, 0.62450103]],

         [[0.93768901, 0.76601963],
          [0.77185702, 0.72760388]]],


        [[[0.13526894, 0.75926133],
          [0.96091066, 0.3330899 ]],

         [[0.16961815, 0.63986495],
          [0.53778978, 0.46026438]]]],



       [[[[0.00669761, 0.97969957],
          [0.73168131, 0.30723009]],

         [[0.43726366, 0.94069781],
          [0.9093014 , 0.01033381]]],


        [[[0.07759597, 0.79503089],
          [0.81766019, 0.69781707]],

         [[0.39541757, 0.31389489],
          [0.88890148, 0.04951043]]]],



       [[[[0.98514268, 0.7652908 ],
          [0.90633407, 0.25113209]],

         [[0.1470607

In [138]:
random_array.ndim

5

In [139]:
len(random_array)

5

In [78]:
reshaped_arr

array([[1, 2, 3, 4, 5]])

In [79]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
# Perform linear algebra operations
product = np.dot(reshaped_arr, arr2)

ValueError: shapes (1,5) and (3,3) not aligned: 5 (dim 1) != 3 (dim 0)

In [81]:
# Compute the mean of the array
mean_value = np.mean(arr2)

# Generate random numbers
random_array = np.random.rand(3, 3)

# Perform linear algebra operations
# product = np.dot(arr2, reshaped_arr)

# Print the results
print(result1)
print(result2)
print(reshaped_arr)
print(mean_value)
print(random_array)
# print(product)

[11 12 13 14 15]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[1 2 3 4 5]]
5.0
[[0.00521537 0.69779507 0.51194799]
 [0.77247084 0.88862299 0.11130008]
 [0.20307493 0.23144078 0.97257557]]


In [82]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(arr)
row_sums = np.sum(arr, axis=1)

print(total_sum)  # Output: 21
print(row_sums)   # Output: [6 15]


21
[ 6 15]


In [83]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
average = np.mean(arr)
row_means = np.mean(arr, axis=1)

print(average)    # Output: 3.5
print(row_means)  # Output: [2. 5.]


3.5
[2. 5.]


In [169]:
import numpy as np

arr = np.array([[10, 2, 30], [4, 5, 60],[7,8,70]])
max_val = np.max(arr)
col_min = np.min(arr, axis=0)

print(max_val)    # Output: 6
print(col_min)   # Output: [1 2 3]


70
[ 4  2 30]


In [85]:
import numpy as np

values = np.linspace(0, 10, num=5)

print(values)  # Output: [ 0.   2.5  5.   7.5 10. ]


[ 0.   2.5  5.   7.5 10. ]


In [86]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Concatenate along the 0th axis (default)
result = np.concatenate((arr1, arr2, arr3))

print(result)
# Output: [1 2 3 4 5 6 7 8 9]


[1 2 3 4 5 6 7 8 9]


In [87]:
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.array([[7, 8, 9]])

# Vertically stack arrays
result = np.vstack((arr1, arr2, arr3))

print(result)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Horizontally stack arrays
result = np.hstack((arr1, arr2, arr3))

print(result)
# Output: [1 2 3 4 5 6 7 8 9]


[1 2 3 4 5 6 7 8 9]


In [89]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print(result)
# Output:
# [[19 22]
#  [43 50]]


[[19 22]
 [43 50]]


In [90]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
inverse = np.linalg.inv(matrix)

print(inverse)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


[[-2.   1. ]
 [ 1.5 -0.5]]


In [91]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [3, 4]])

# Perform eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
# Output: [0.37228132 4.62771868]

print(eigenvectors)
# Output:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [92]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# Perform singular value decomposition
U, s, V = np.linalg.svd(matrix)

print("U:", U)
print("s:", s)
print("V:", V)


U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
s: [9.52551809 0.51430058]
V: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [171]:
# Split an array
arr5 = np.array([1, 2, 3, 4, 5,8])
split_arr = np.split(arr5, 3)

print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 8])]


In [95]:
import numpy as np

# Concatenate arrays
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr3, arr4))

print(concatenated_arr)
# Output: [1 2 3 4 5 6]

# Split an array
arr5 = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr5, 2)

print(split_arr)
# Output: [array([1, 2, 3]), array([4, 5, 6])]

# Stack arrays vertically (row-wise)
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
vertical_stack = np.vstack((arr6, arr7))

print(vertical_stack)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Stack arrays horizontally (column-wise)
arr8 = np.array([1, 2, 3])
arr9 = np.array([4, 5, 6])
horizontal_stack = np.hstack((arr8, arr9))

print(horizontal_stack)
# Output: [1 2 3 4 5 6]


[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [96]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
subarrays = np.split(arr, 3)

print(subarrays)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


In [1]:
import numpy as np

arr = np.array([1, 2, 4, 5, 3, 4, 5, 6])
indices = [2, 4]
subarrays = np.split(arr, indices)

print(subarrays)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([4, 5]), array([3, 4, 5, 6])]


In [107]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
subarrays = np.split(arr, 2, axis=0)

print(subarrays)
# Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]


[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [109]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
subarrays = np.array_split(arr, 2)

print(subarrays)
# Output: [array([1, 2]), array([3, 4]), array([5])]


[array([1, 2, 3]), array([4, 5])]


In [110]:
import numpy as np

# Create an array of mixed numbers and strings
arr = np.array([1, 2, 'apple', 4, 'banana', 'watermelon', 7, 'orange', 'grape', 10])

# Define the string to split at
split_string = 'orange'

# Find the indices where the split string occurs
split_indices = np.where(arr == split_string)[0]

# Split the array based on the indices
subarrays = np.split(arr, split_indices + 1)

print(subarrays)


[array(['1', '2', 'apple', '4', 'banana', 'watermelon', '7', 'orange'],
      dtype='<U21'), array(['grape', '10'], dtype='<U21')]


In [1]:
!pip install python-dotenv==1.0.0
